version: "3.3"

services:
  opa:
    image: openpolicyagent/opa:latest
    container_name: opa
    platform: linux/amd64
    ports:
      - "8181:8181"
    volumes:
      - ./policy:/app/policy
    command: [
      "run",
      "--server",
      "--addr",
      "0.0.0.0:8181",
#      "--config-file",
#      "/app/policy/config.yaml",
      "/app/policy/api.rego"
    ]
  backend:
    container_name: backend
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:1.17
#    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - opa
