version: "3.3"

services:
  opa:
    image: openpolicyagent/opa:latest
#    image: openpolicyagent/opa:latest-envoy
    container_name: opa
    platform: linux/amd64
    ports:
      - "8181:8181"
    volumes:
      - ./policy:/app/policy
      - ./data:/app/data
    restart: unless-stopped
    command: [
      "run", "--server",
      "--addr", "0.0.0.0:8181",
      "--log-level", "debug",
      "--log-level", "info",
      "--authorization", "basic",
#            "--config-file",
      "/app/policy/auth.rego",
    ]
  backend:
    container_name: backend
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: nginx:1.17
#    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - opa
